add mysql database support
probe-ai/probe-client pull request #8
Opened 2023-04-28 10:33 UTC by suhailmalik07

2023-05-01 05:31 UTC, chandel-19 requested changes

2023-05-01 05:31 UTC, chandel-19 commented on src/client-db/mysql.util.ts
>    }
why this function is needed? why not directly use `getDbMetadataForTables`?

2023-05-01 05:31 UTC, chandel-19 commented on src/client-db/mysql.util.ts
> +          return reject(`Error querying MySQL: ${error}`);
```suggestion
         reject(`Error querying MySQL: ${error}`);
```
?

2023-05-01 05:31 UTC, chandel-19 commented on src/client-db/mysql.util.ts
> +          ...result.map((row) => row[column.name]).map(String),
tested for different data type? does String() works for date, datetime and json?

2023-05-02 06:48 UTC, suhailmalik07 commented on src/client-db/mysql.util.ts
>    }
Will cleanup this factory pattern with cancel query

2023-05-02 06:48 UTC, suhailmalik07 commented on src/client-db/mysql.util.ts
> +          return reject(`Error querying MySQL: ${error}`);
otherwise it will not stop and will go after this function and resolve() will be called, so can't remove this.

2023-05-02 06:48 UTC, suhailmalik07 commented on src/client-db/mysql.util.ts
> +          ...result.map((row) => row[column.name]).map(String),
Good catch changed this for `JSON.stringify`.

2023-05-02 07:34 UTC, chandel-19 approved these changes

2023-05-02 07:34 UTC, chandel-19 commented on src/client-db/mysql.util.ts
> +          ...result.map((row) => row[column.name]).map(JSON.stringify),
sabke liye json stringy karna hai? merging for now

2023-05-02 07:34 UTC, merged